language: java

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:

script:
  - mvn clean package -DskipTests=true

after_success:
  - cd ./target
  - git init
  - git config user.name "Starrier"
  - git config user.email "starrier@starrier.com"
  - git add .
  - git commit -m "travis-ci"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

env:
  global:
    - GH_REF=https://github.com/Starrier/commons.git